### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by net-tech** [igrek8/bullmq-prometheus#37]
Hi there, are there any existing plans to add TypeScript types for this project? Thanks.

**Comment by igrek8** [comment]
Hello @net-tech, I haven't planned to introduce TypeScript as I viewed this project solely as runnable. However, it should not be difficult to convert it to TypeScript. Would you like to create a PR for this?

**Comment by net-tech** [comment]
Sure I'll convert to typescript

**Comment by igrek8** [comment]
@net-tech have you had time to look into this?

**Comment by net-tech** [comment]
> @net-tech have you had time to look into this?

Sorry I completely forgot about this; I'll see if I can get a PR out this or next week

**Comment by net-tech** [comment]
Hi @igrek8, I'm looking into this again. Would this be the correct type for `metrics` in the code?

```ts
interface Metrics {
  [key: string]: {
    [db: string]: {
      [queue: string]: number;
    };
  };
}
```
